// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockV3Aggregator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockV3Aggregator";
  readonly sourceName: "contracts/mocks/MockV3Aggregator.sol";
  readonly abi: [{"inputs":[{"internalType":"int256","name":"initialAnswer","type":"int256"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"latestRoundData","outputs":[{"internalType":"uint80","name":"","type":"uint80"},{"internalType":"int256","name":"","type":"int256"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"uint80","name":"","type":"uint80"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"int256","name":"nextAnswer","type":"int256"}],"name":"setAnswer","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x60a034605d57601f61017238819003918201601f19168301916001600160401b03831184841017606157808492602094604052833981010312605d575160086080525f554260015560405160fc908161007682396080518160a20152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe60808060405260043610156011575f80fd5b5f3560e01c908163313ce56714608d5750806399213cd81460735763feaf968c146039575f80fd5b34606f575f366003190112606f5760a05f5460015460405191600183526020830152806040830152606082015260016080820152f35b5f80fd5b34606f576020366003190112606f576004355f5542600155005b34606f575f366003190112606f5760209060ff7f0000000000000000000000000000000000000000000000000000000000000000168152f3fea264697066735822122000380409335c7d77267690b565988f60c9656ff628895fb6481f02537b38782864736f6c634300081c0033";
  readonly deployedBytecode: "0x60808060405260043610156011575f80fd5b5f3560e01c908163313ce56714608d5750806399213cd81460735763feaf968c146039575f80fd5b34606f575f366003190112606f5760a05f5460015460405191600183526020830152806040830152606082015260016080820152f35b5f80fd5b34606f576020366003190112606f576004355f5542600155005b34606f575f366003190112606f5760209060ff7f0000000000000000000000000000000000000000000000000000000000000000168152f3fea264697066735822122000380409335c7d77267690b565988f60c9656ff628895fb6481f02537b38782864736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {"4748":[{"length":32,"start":162}]};
  readonly inputSourceName: "project/contracts/mocks/MockV3Aggregator.sol";
  readonly buildInfoId: "solc-0_8_28-a1c665f2bba152003a183eb6c9a13c5a871cb217";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockV3Aggregator"]: MockV3Aggregator$Type;
    ["contracts/mocks/MockV3Aggregator.sol:MockV3Aggregator"]: MockV3Aggregator$Type;
  }
}